import { db, documentVersions, documents } from "@repo/db";
import { eq } from "drizzle-orm";
import { canExportFiling } from "../../../../lib/demo-role-constants";
import { getDemoRole } from "../../../../lib/demo-role-server";

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export async function GET(
  _request: Request,
  context: { params: Promise<{ versionId: string }> },
) {
  const { versionId } = await context.params;
  const role = await getDemoRole();
  if (!canExportFiling(role)) {
    return new Response("Forbidden — switch to reviewer or admin on /compliance", {
      status: 403,
    });
  }

  const [row] = await db
    .select({
      version: documentVersions,
      document: documents,
    })
    .from(documentVersions)
    .innerJoin(documents, eq(documents.id, documentVersions.documentId))
    .where(eq(documentVersions.id, versionId))
    .limit(1);

  if (!row) {
    return new Response("Not found", { status: 404 });
  }

  const title = escapeHtml(row.document.title);
  const ver = escapeHtml(row.version.version);
  const body = escapeHtml(row.version.content);
  const slug = escapeHtml(row.document.slug);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Demo exhibit — ${title} (${ver})</title>
  <meta name="robots" content="noindex" />
</head>
<body>
  <header style="font-family:system-ui,sans-serif;padding:1rem;border-bottom:1px solid #ccc">
    <h1 style="font-size:1.1rem;margin:0">${title}</h1>
    <p style="margin:0.35rem 0 0;font-size:0.85rem;color:#444">
      Version ${ver} · slug ${slug} · <strong>DEMO ONLY — NOT FOR EDGAR LIVE</strong>
    </p>
  </header>
  <main style="font-family:system-ui,sans-serif;padding:1rem;max-width:52rem">
    <pre style="white-space:pre-wrap;word-break:break-word;font-size:0.9rem;line-height:1.45">${body}</pre>
  </main>
  <footer style="font-family:system-ui,sans-serif;padding:1rem;border-top:1px solid #ccc;font-size:0.75rem;color:#666">
    Generated by disclosure-dag-demo for local demonstration. Inline XBRL (if any) is not embedded in this stub export.
  </footer>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="demo-edgar-exhibit-${versionId.slice(0, 8)}.html"`,
    },
  });
}
