import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div
          style={{
            padding: "6px 12px",
            fontSize: 12,
            background: "#422006",
            color: "#fef3c7",
            fontFamily: "ui-monospace, monospace",
          }}
        >
          <strong>docs</strong> · port 3001 — this app has no <code>/funds</code>. Open{" "}
          <a href="http://localhost:3000/funds" style={{ color: "#fde047" }}>
            localhost:3000/funds
          </a>{" "}
          for the DB demo.
        </div>
        {children}
      </body>
    </html>
  );
}
